<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Homeoffice.Contracts\Homeoffice.Contracts.csproj" />
    <ProjectReference Include="..\Homeoffice.Services\Homeoffice.Services.csproj" />
  </ItemGroup>

</Project>
