<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.12.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="MimeKit" Version="4.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Homeoffice.Contracts\Homeoffice.Contracts.csproj" />
    <ProjectReference Include="..\Homeoffice.DataAccess\Homeoffice.DataAccess.csproj" />
    <ProjectReference Include="..\Homeoffice.Models\Homeoffice.Models.csproj" />
  </ItemGroup>

</Project>
